language: node_js
node_js:
  - '1'
  - '4'
  - '5'
  - '6'
  - 'node'
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install yarn && ./node_modules/.bin/yarn install --ignore-optional
  - bower install --force
addons:
  code_climate:
    repo_token:
        secure: "d/wFwGhBdJRPTca6FeDees/h/YUP0z4MvQJAxeisyo//+tfhUMEy43hBcdg88LYtS0FQou7oucKK8PDX4BgIhIMPFbDMl1VQ7bRfjWaccI8mH4DvjkJTWL19pUjj3IunZKuWnEHVhHr2Pp7JacgD+S4t4wV/Lh5rw/VY+dE4cmg="
after_script:
  - cat coverage/phantomjs/lcov.info | codeclimate
